In [24]:
import pandas as pd

# load dataset :
df = pd.read_csv("../data/Spotify_Tracks.csv")

# Basic sanity check :
df.head()

,genre,artist_name,track_name,track_id,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence
0,Movie,Henri Salvador,C'est beau de faire un Show,0BRjO6ga9RKCKjfDqeFgWV,0,0.611,0.389,99373,0.910,0.000,C#,0.3460,-1.828,Major,0.0525,166.969,4/4,0.814
1,Movie,Martin & les fées,Perdu d'avance (par Gad Elmaleh),0BjC1NfoEOOusryehmNudP,1,0.246,0.590,137373,0.737,0.000,F#,0.1510,-5.559,Minor,0.0868,174.003,4/4,0.816
2,Movie,Joseph Williams,Don't Let Me Be Lonely Tonight,0CoSDzoNIKCRs124s9uTVy,3,0.952,0.663,170267,0.131,0.000,C,0.1030,-13.879,Minor,0.0362,99.488,5/4,0.368
3,Movie,Henri Salvador,Dis-moi Monsieur Gordon Cooper,0Gc6TVm52BwZD07Ki6tIvf,0,0.703,0.240,152427,0.326,0.000,C#,0.0985,-12.178,Major,0.0395,171.758,4/4,0.227
4,Movie,Fabien Nataf,Ouverture,0IuslXpMROHdEPvSl1fTQK,4,0.950,0.331,82625,0.225,0.123,F,0.2020,-21.150,Major,0.0456,140.576,4/4,0.390

In [ ]:
# shape of data :
df.shape

In [ ]:
# columns name :
df.columns

In [ ]:
# data types & missing values :
df.info()

In [ ]:
# quick stats :
df.describe()

In [ ]:
# TO CHECK DATA QUALITY :
# === missing values per columns ===
df.isna().sum().sort_values(ascending=False)

In [ ]:
# DUPILCATED ROWS :
df.duplicated().sum()

In [ ]:
#  POPULARITY sanity check :
df["popularity"].describe()

df["popularity"].value_counts().head(10)

In [20]:
#==== SEGMENT A : EMERGING / ACTIVE TRACKS 
active_df = df[df["popularity"]>0]
active_df.shape

# comparing popularity distribution
active_df["popularity"].describe()

count    226413.000000
mean         42.274066
std          17.077129
min           1.000000
25%          30.000000
50%          44.000000
75%          55.000000
max         100.000000
Name: popularity, dtype: float64

In [21]:
# STEP 1 :

# CORE ANALYSIS , QUES : Do audio features systematically changes as popularity increases ?
# popularity bucket :
def popularity_bucket(p):
    if p < 30 :
        return "Low" 
    elif p < 60 :
        return "Medium"
    else :
        return "High"

active_df["popularity_level"] = active_df["popularity"].apply(popularity_bucket)

active_df["popularity_level"].value_counts()

popularity_level
Medium    135932
Low        54027
High       36454
Name: count, dtype: int64

In [29]:
# STEP 2 : COMPARING AUDIO FEATURES ACROSS POPULARITY LEVELS
audio_features = [
    "danceability","energy","acousticness","speechiness","valence","tempo","loudness"
]
active_df.groupby("popularity_level")[audio_features].mean()

,danceability,energy,acousticness,speechiness,valence,tempo,loudness
popularity_level,,,,,,,
High,0.630130,0.640634,0.227710,0.107316,0.487068,120.486763,-6.930294
Low,0.487086,0.512091,0.541733,0.195847,0.426709,113.862142,-12.098718
Medium,0.560036,0.585802,0.323485,0.094601,0.453787,118.507015,-9.065222